# Generated by Django 5.0 on 2025-11-25 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日付')),
                ('meal_name', models.CharField(max_length=100, verbose_name='食事名')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('recipe', models.TextField(blank=True, verbose_name='レシピ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meal_photos/', verbose_name='写真')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
